version: "3"
services:
  db:
    image: mysql:5.7
    user: "1000:50"
    command: --innodb_use_native_aio=0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: docker_test
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./build/mysql:/var/lib/mysql

  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/application
      - ./build/php.ini:/usr/local/etc/php/php.ini
    links:
      - db

  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./:/application
      - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123456
    links:
      - db
